# Generated by Django 5.2.6 on 2025-09-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orderitem_price'),
        ('shop', '0012_serviceplan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.serviceplan'),
        ),
    ]
