# Generated by Django 4.2.24 on 2025-09-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_models_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_consults', to=settings.AUTH_USER_MODEL),
        ),
    ]
