# Generated by Django 5.2.6 on 2025-09-15 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_manual_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Mã màu hex, ví dụ #EF4444', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Mã màu phải ở dạng #RGB hoặc #RRGGBB.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
