# Generated by Django 5.2.6 on 2025-09-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color_hex',
        ),
    ]
