# Generated by Django 5.2.6 on 2025-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
