# Generated by Django 5.2.6 on 2025-09-23 09:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orderitem_price'),
        ('shop', '0011_alter_product_supplier_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: Gói 1 tháng / 1 năm…', max_length=120)),
                ('term', models.CharField(choices=[('MONTH', '1 tháng'), ('QUARTER', '1 quý (3 tháng)'), ('YEAR', '1 năm'), ('CUSTOM', 'Tùy chỉnh (ngày)')], db_index=True, default='MONTH', max_length=10)),
                ('custom_days', models.PositiveIntegerField(default=0, help_text='Chỉ dùng khi term=CUSTOM')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='shop.product')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hiệu lực'), ('EXPIRED', 'Hết hạn'), ('CANCELLED', 'Đã hủy')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orderitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='shop.serviceplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'ends_at'], name='shop_subscr_user_id_86c34e_idx')],
            },
        ),
    ]
