# Generated by Django 5.2.6 on 2025-09-24 07:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shop.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_serviceplan_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering', 'name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu tư vấn', 'verbose_name_plural': 'Yêu cầu tư vấn'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Mục đơn hàng', 'verbose_name_plural': 'Mục đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lượt xem trang', 'verbose_name_plural': 'Lượt xem trang'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Ảnh sản phẩm', 'verbose_name_plural': 'Ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='serviceplan',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Gói dịch vụ', 'verbose_name_plural': 'Gói dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-started_at'], 'verbose_name': 'Đăng ký dịch vụ', 'verbose_name_plural': 'Đăng ký dịch vụ'},
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='shop_pagevi_created_95c979_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='shop_pagevi_session_114745_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_created_ddfb00_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='shop_subscr_user_id_86c34e_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='compare_price',
            new_name='sale_price',
        ),
        migrations.AlterUniqueTogether(
            name='serviceplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='order_item',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageviews', to='shop.product'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('done', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='new', max_length=12),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('refunded', 'Hoàn tiền')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shop.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='custom_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='term',
            field=models.CharField(choices=[('month', 'Theo tháng (30 ngày)'), ('quarter', 'Theo quý (90 ngày)'), ('year', 'Theo năm (365 ngày)'), ('custom', 'Tùy chỉnh (custom_days)')], default='month', max_length=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hiệu lực'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn')], default='active', max_length=12),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'ordering'], name='shop_catego_is_acti_bb665f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['product', 'status'], name='shop_consul_product_4c83a7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='shop_order_status_65feda_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='shop_order_user_id_f8b1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='shop_orderi_order_i_08c5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['-created_at'], name='shop_pagevi_created_57f438_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path'], name='shop_pagevi_path_6ede83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='shop_produc_is_acti_2d6428_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='shop_produc_categor_6c2d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceplan',
            index=models.Index(fields=['product', 'ordering'], name='shop_servic_product_3fda6c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', '-started_at'], name='shop_subscr_status_8ab402_idx'),
        ),
    ]
