# Generated by Django 5.2.6 on 2025-09-17 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('link_url', models.URLField(blank=True)),
                ('link_label', models.CharField(blank=True, help_text='Ví dụ: Đọc tại nguồn', max_length=120)),
                ('crop_x', models.PositiveIntegerField(default=0)),
                ('crop_y', models.PositiveIntegerField(default=0)),
                ('crop_w', models.PositiveIntegerField(default=0)),
                ('crop_h', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-published_at'],
            },
        ),
    ]
