# Generated by Django 5.2.6 on 2025-09-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link_label',
            field=models.CharField(blank=True, default='', help_text='Ví dụ: Đọc tại nguồn', max_length=120),
        ),
        migrations.AlterField(
            model_name='news',
            name='link_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
