# Generated by Django 5.2.6 on 2025-09-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_link_label_alter_news_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
