# Generated by Django 5.2.6 on 2025-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='crop_h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='crop_w',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='crop_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='crop_y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
