# Generated by Django 5.2.6 on 2025-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_crop_h_alter_news_crop_w_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link_label',
            field=models.CharField(blank=True, default='', help_text='Ví dụ: Đọc tại nguồn / Xem ngay', max_length=120),
        ),
    ]
